"""
A1 测试: ReportWriter 接 pdf_context + 上下文工具（多级压缩新链路）

覆盖（沿用 P2 Analyst 门控测试模式）:
- flag 开启走新链路: 装配 + 3 工具 + pdf_context 注入 prompt + 审计留痕回流
- flag 关闭保持旧路径（防回归）
- 修订模式: 反馈进 prompt 且仍挂工具（供核对反馈涉及的数字）
- LLM 失败/空返回: 降级报告 + 工具留痕不丢
- l2/l3 直接读 state 复用（本函数不构建，A3 的读侧前提）
"""

import pytest

from graphs.state import create_initial_state
from extractors.l1_builder import build_l1


def _tiny_l1():
    pages = [
        {"page_idx": 0, "items": [
            {"type": "heading", "content": "合并利润表", "level": 2},
            {"type": "table", "content": (
                "<table><tr><td>项目</td><td>2024年</td><td>2023年</td></tr>"
                "<tr><td>营业收入</td><td>204.42</td><td>195.14</td></tr></table>"
            ), "caption": [], "footnote": []},
            {"type": "heading", "content": "经营讨论", "level": 2},
            {"type": "text", "content": "公司营收稳健增长。"},
        ]},
    ]
    return build_l1(pages, companies=["复星医药"])


def _state_for_writer():
    st = create_initial_state("撰写复星医药投资分析报告", pdf_path="")
    st["pdf_l1"] = _tiny_l1()
    st["analysis_result"] = "## 财务表现分析\n营收 204.42 亿元，增长稳健 [P 0]"
    st["financial_data"] = {"stock_info": {"name": "复星医药", "code": "600196"}}
    return st


# ---------------------------------------------------------------------------
# 1. flag 开启 → 新链路
# ---------------------------------------------------------------------------

def test_writer_strips_llm_preamble(monkeypatch):
    """[A5] 工具循环最终回复的元评论前缀必须被剥离，报告从首个 H1 开始"""
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)
    # 带英文元评论前缀 + 中间无干扰 H1 的回复
    noisy = 'I now have comprehensive data. Let me compile.\n\n---\n\n# 复星医药投资分析报告\n\n## 一、核心结论\n稳健 [P 0]'
    monkeypatch.setattr(rw, "safe_invoke_with_tools",
                        lambda *a, **kw: {"error": False, "content": noisy, "tool_calls": [], "rounds": 1})

    out = rw.report_writer_node(_state_for_writer())

    assert out["final_report"].lstrip().startswith("# "), "报告必须从 H1 开始"
    assert "I now have" not in out["final_report"], "元评论不得泄漏进报告"
    assert "复星医药投资分析报告" in out["final_report"]
    # 无 H1 的回复（纯文本）：原样保留，不误删
    monkeypatch.setattr(rw, "safe_invoke_with_tools",
                        lambda *a, **kw: {"error": False, "content": "OK 纯文本报告内容", "tool_calls": [], "rounds": 1})
    out2 = rw.report_writer_node(_state_for_writer())
    assert "纯文本报告内容" in out2["final_report"]


def test_writer_uses_multilevel_path_when_flag_on(monkeypatch):
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)

    captured = {}

    def fake_with_tools(system_prompt, user_message, tools, **kw):
        captured["n_tools"] = len(tools)
        captured["tool_names"] = sorted(t.name for t in tools)
        captured["prompt"] = system_prompt
        return {"error": False, "content": "# 复星医药投资分析报告\n营收 204.42 亿元 [P 0]", "tool_calls": [], "rounds": 1}

    monkeypatch.setattr(rw, "safe_invoke_with_tools", fake_with_tools)

    out = rw.report_writer_node(_state_for_writer())

    assert "204.42" in out["final_report"]
    assert captured["n_tools"] == 3, "必须挂载 3 个上下文工具"
    assert captured["tool_names"] == ["fetch_context", "query_fact", "search_section"]
    # 装配后的年报内容必须进 prompt（不再消费 pdf_summary）
    assert "PDF 年报内容" in captured["prompt"]
    assert "204.42" in captured["prompt"], "L1 表格数字必须经装配注入"
    # Analyst 结论是 Writer 的素材基础
    assert "营收 204.42 亿元，增长稳健" in captured["prompt"]
    # 统一后处理（免责声明 + 版本脚注）
    assert "免责" in out["final_report"] or "不构成" in out["final_report"]
    assert "Generated by FinScope" in out["final_report"]
    assert "tool_call_history" in out
    assert out["agent_status"]["report_writer"] == "done"


def test_writer_reuses_state_l2_l3_without_rebuild(monkeypatch):
    """l2/l3 必须直接读 state（Analyst 写回的缓存），Writer 侧零构建"""
    import agents.report_writer as rw
    import extractors.context_assembler as ca
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)
    monkeypatch.setattr(rw, "safe_invoke_with_tools",
                        lambda *a, **kw: {"error": False, "content": "OK 报告", "tool_calls": [], "rounds": 1})

    captured = {}

    def fake_assemble(query, budget, l1, l2=None, l3=None, **kw):
        captured["l2"] = l2
        captured["l3"] = l3
        return {"context": "装配内容", "stats": {"used": 10}, "injected": [], "pointers": []}

    monkeypatch.setattr(ca, "assemble", fake_assemble)

    st = _state_for_writer()
    st["pdf_l2"] = {"s_000": {"section_id": "s_000", "summary": "已缓存摘要"}}
    st["pdf_l3"] = {"text": "全局亮点", "source": "l3_lite_rules"}
    rw.report_writer_node(st)

    assert captured["l2"] == st["pdf_l2"], "l2 必须原样复用 state 缓存"
    assert captured["l3"] == "全局亮点"


# ---------------------------------------------------------------------------
# 2. flag 关闭 → 旧路径（防回归）
# ---------------------------------------------------------------------------

def test_writer_keeps_old_path_when_flag_off(monkeypatch):
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", False)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)
    called_new = {}

    def fake_with_tools(*a, **kw):
        called_new["called"] = True
        return {"error": False, "content": "x"}

    def fake_safe_invoke(system_prompt, user_message, **kw):
        called_new["old_prompt"] = system_prompt
        return {"error": False, "content": "# 旧路径报告\n营收稳健 [P 1]"}

    monkeypatch.setattr(rw, "safe_invoke_with_tools", fake_with_tools)
    monkeypatch.setattr(rw, "safe_invoke", fake_safe_invoke)

    out = rw.report_writer_node(_state_for_writer())

    assert "called" not in called_new, "flag 关闭不得走工具链路"
    assert "旧路径报告" in out["final_report"]
    assert "Generated by FinScope" in out["final_report"], "旧路径后处理行为不变"
    # [A4] 旧路径已无 PDF 内容可消费（pdf_sections/pdf_summary 字段删除），
    # 基础上下文仍含实体/市场数据/分析结论
    assert "深度分析结论" in called_new["old_prompt"]
    assert "PDF 全文摘要" not in called_new["old_prompt"]


# ---------------------------------------------------------------------------
# 3. 审计留痕 + 修订模式 + 降级
# ---------------------------------------------------------------------------

def test_writer_audit_history_passthrough(monkeypatch):
    """新链路工具调用历史必须回流 state（银行审计），agent 标记为 report_writer"""
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)

    st = _state_for_writer()
    st["tool_call_history"] = [{"agent": "financial_analyst", "tool": "query_fact", "ts": "x"}]

    def fake_with_tools(system_prompt, user_message, tools, max_rounds=None, on_tool_call=None):
        if on_tool_call:
            on_tool_call("query_fact", {"metric": "营业收入"}, "命中 204.42")
        return {"error": False, "content": "OK", "tool_calls": [{"tool": "query_fact"}], "rounds": 1}

    monkeypatch.setattr(rw, "safe_invoke_with_tools", fake_with_tools)

    out = rw.report_writer_node(st)
    calls = out.get("tool_call_history", [])
    assert len(calls) == 2, "Analyst 旧留痕 + Writer 本次调用都必须保留"
    last = calls[-1]
    assert last["agent"] == "report_writer"
    assert last["tool"] == "query_fact"
    assert "ts" in last and "result_len" in last, "审计字段必须齐全（谁/何时/工具/参数/返回体量）"


def test_writer_revision_mode_with_tools(monkeypatch):
    """修订模式: 反馈与上一版进 prompt，且仍挂工具（核对反馈涉及的数字）"""
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)

    captured = {}

    def fake_with_tools(system_prompt, user_message, tools, **kw):
        captured["prompt"] = system_prompt
        captured["n_tools"] = len(tools)
        return {"error": False, "content": "# 修订版报告", "tool_calls": [], "rounds": 1}

    monkeypatch.setattr(rw, "safe_invoke_with_tools", fake_with_tools)

    st = _state_for_writer()
    st["review_feedback"] = "报告写营收 204.43 亿元与事实表 204.42 不符，请修正 [P 0]"
    st["prev_final_report"] = "# 旧报告\n营收 204.43 亿元 [P 0]"
    out = rw.report_writer_node(st)

    assert "修订" in captured["prompt"]
    assert "204.43 亿元与事实表" in captured["prompt"], "审查反馈必须进 prompt"
    assert "旧报告" in captured["prompt"], "上一版报告必须进 prompt"
    assert captured["n_tools"] == 3, "修订模式同样挂 3 工具供核对"
    assert "修订版报告" in out["final_report"]


def test_writer_fallback_on_llm_error_new_path(monkeypatch):
    """新链路 LLM 失败: 降级报告 + 工具留痕不丢（不再二次调旧路径浪费调用）"""
    import agents.report_writer as rw
    from utils.config import get_settings

    monkeypatch.setattr(get_settings(), "USE_MULTILEVEL_COMPRESSION", True)
    monkeypatch.setattr(rw, "is_llm_ready", lambda: True)

    def fake_with_tools(*a, **kw):
        return {"error": True, "message": "API 超时"}

    old_called = {}

    def fake_safe_invoke(*a, **kw):
        old_called["called"] = True
        return {"error": False, "content": "x"}

    monkeypatch.setattr(rw, "safe_invoke_with_tools", fake_with_tools)
    monkeypatch.setattr(rw, "safe_invoke", fake_safe_invoke)

    out = rw.report_writer_node(_state_for_writer())

    assert "简要版" in out["final_report"] or "免责" in out["final_report"], "必须产出降级报告"
    assert "old_called" not in old_called, "新链路失败不得回退再打一次旧路径 LLM"
    assert out["agent_status"]["report_writer"] == "done"
